### ISSUE TITLE
Building on Windows fails

### ISSUE THREAD

**Issue by tksuoran** [vorth/vzome-desktop#2]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project vzome-desktop: Compilation failure: Compilation failure:
[ERROR] \git\vzome-desktop\src\main\java\org\vorthmann\j3d\MacAdapter.java:[9,21] error: package com.apple.eawt does not exist
...
Followed by more errors related to MacAdapter.

**Comment by vorth** [comment]
Hi, Timo,

Thank you.  This was just pointed out to me yesterday.  Apparently javac picks up that class on a Mac in the extensions folder.  I’ll work out how to make the build platform-specific, and use reflection to instantiate the class.

I’ve included my personal email here, if you want to use it and not have to go through github.

Scott

**Comment by vorth** [comment]
Timo,

I have pushed a new "nomac" branch.  It has these changes:

1. a gradle-based build, with the MacAdapter class omitted from the build except on the Mac
2. the Platform class now uses reflection to invoke MacAdapter.setupListener(), so no attempt to load the class will occur on non-Windows platforms

The gradle build is not self-contained yet, so you'll have to do the Maven build steps once first, or at least the steps that install the Java3d JARs in the local Maven repo.  After that, just do "gradlew build".  The "gradlew" command will bootstrap gradle for you.

You'll need to adjust the classpath in your .bat script, to pick up the build/classes folder.

**Comment by vorth** [comment]
fixed by 5d60602208ff39c630ca338c36d214a339d29d75
